import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import Script from 'next/script'
import { useState } from 'react'
import mongoose from 'mongoose'
import Books from '../models/Books'

export default function Home({ products }) {
  const [books, setbooks] = useState(products)
  return <>
    <Head>
      <title>CuteOwl | HOME</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/store-logo-h.svg" />
    </Head>


    <div className="bg-gray-200 font-sans leading-normal tracking-normal">


      <div className={`w-full m-0 p-0 -top-10 bg-cover bg-bottom ${styles.mainbg} z-0`} >
        <Image src="/cover.svg" alt="" className='w-full h-[60vh] sm:h-[50vh] z-0 ' height={700} width={2000} />
      </div>


      <div className="container px-4 md:px-0 max-w-6xl mx-auto z-10 mt-5 ">

        <div className="mx-0 sm:mx-6">

          <div className="bg-gray-200 w-full text-xl md:text-2xl text-gray-800 leading-normal rounded-t">


            <div className="flex h-full bg-white rounded overflow-hidden shadow-lg">

              <Link href={'/deals'}><a className="flex flex-wrap no-underline hover:no-underline">
                <div className="w-full md:w-2/3 rounded-t">
                  <img src="https://source.unsplash.com/collection/494263/800x600" className="h-full w-full shadow" />
                </div>

                <div className="w-full md:w-1/3 flex flex-col flex-grow flex-shrink">
                  <div className="flex-1 bg-white rounded-t rounded-b-none overflow-hidden shadow-lg">
                    <p className="w-full text-gray-600 text-xs md:text-sm pt-6 px-6">GETTING STARTED</p>
                    <div className="w-full font-bold text-xl text-gray-900 px-6">👋 Welcome fellow Tailwind CSS and Ghost fan</div>
                    <p className="text-gray-800 font-serif text-base px-6 mb-5">
                      This starter template is an attempt to replicate the default Ghost theme "Casper" using Tailwind CSS and vanilla Javascript.
                    </p>
                  </div>

                  <div className="flex-none mt-auto bg-white rounded-b rounded-t-none overflow-hidden shadow-lg p-6">
                    <div className="flex items-center justify-between">
                      <img className="w-8 h-8 rounded-full mr-4 avatar" data-tippy-content="Author Name" src="http://i.pravatar.cc/300" alt="Avatar of Author" />
                      <p className="text-gray-600 text-xs md:text-sm">1 MIN READ</p>
                    </div>
                  </div>
                </div>

              </a></Link>
            </div>

            <div className="flex flex-wrap justify-between pt-12 -mx-6">

              {/* Books Column */}
              <div class="flex flex-wrap w-full mb-2">
                <div class="lg:w-1/2 w-full mb-6 lg:mb-0">
                  <h1 class="sm:text-3xl text-2xl font-medium title-font mb-2 text-gray-900">Most Popular Books</h1>
                  <div class="h-1 w-20 bg-blue-500 rounded"></div>
                </div>
              </div>
          {books && books.map((item) => {
                return <Link href={`/product/${item.slug}`}><div className="w-full md:w-1/3 p-6 flex flex-col flex-grow flex-shrink">
                  <div className="flex-1 bg-white rounded-t-lg rounded-b-none overflow-hidden shadow-lg">
                    <a href="#" className="flex flex-wrap no-underline hover:no-underline">
                      <img src={item.img} className="h-64 object-scale-down w-full rounded-t pb-6" />
                      <p className="w-full text-gray-600 text-xs md:text-sm px-6 capitalize">{item.category}</p>
                      <div className="w-full font-bold text-xl text-gray-900 px-6">{item.title.substr(0, 20)}...</div>
                      <p className="text-gray-800 font-serif text-base px-6 mb-5">
                        {item.desc.substr(0, 100)}...
                      </p>
                    </a>
                  </div>
                  <div className="flex-none mt-auto bg-white rounded-b rounded-t-none overflow-hidden shadow-lg p-6">
                    <div className="flex items-center justify-between">
                      {/* <img className="w-8 h-8 ml-2 rounded-full mr-4 avatar" data-tippy-content="Author Name" src="http://i.pravatar.cc/300" alt="Avatar of Author" /> */}
                      <p className='flex flex-col'><span className=' text-sm'>by</span> <span className='font-bold text-xl'>{item.author}</span></p>
                      <p className="text-gray-600 text-2xl font-bold md:text-xl">₹{item.price}</p>
                    </div>
                  </div>
                </div></Link>

              })}






              <div className="w-full md:w-1/2 p-6 flex flex-col flex-grow flex-shrink">
                <div className="flex-1 bg-white rounded-t rounded-b-none overflow-hidden shadow-lg">
                  <a href="#" className="flex flex-wrap no-underline hover:no-underline">
                    <img src="https://source.unsplash.com/collection/3657445/800x600" className="h-full w-full rounded-t pb-6" />
                    <p className="w-full text-gray-600 text-xs md:text-sm px-6">GETTING STARTED</p>
                    <div className="w-full font-bold text-xl text-gray-900 px-6">Lorem ipsum dolor sit amet.</div>
                    <p className="text-gray-800 font-serif text-base px-6 mb-5">
                      Lorem ipsum eu nunc commodo posuere et sit amet ligula.
                    </p>
                  </a>
                </div>
                <div className="flex-none mt-auto bg-white rounded-b rounded-t-none overflow-hidden shadow-lg p-6">
                  <div className="flex items-center justify-between">
                    <img className="w-8 h-8 rounded-full mr-4 avatar" data-tippy-content="Author Name" src="http://i.pravatar.cc/300" alt="Avatar of Author" />
                    <p className="text-gray-600 text-xs md:text-sm">1 MIN READ</p>
                  </div>
                </div>
              </div>


              <div className="w-full md:w-1/2 p-6 flex flex-col flex-grow flex-shrink">
                <div className="flex-1 flex-row bg-white rounded-t rounded-b-none overflow-hidden shadow-lg">
                  <a href="#" className="flex flex-wrap no-underline hover:no-underline">
                    <img src="https://source.unsplash.com/collection/764827/800x600" className="h-full w-full rounded-t pb-6" />
                    <p className="w-full text-gray-600 text-xs md:text-sm px-6">GETTING STARTED</p>
                    <div className="w-full font-bold text-xl text-gray-900 px-6">Lorem ipsum dolor sit amet.</div>
                    <p className="text-gray-800 font-serif text-base px-6 mb-5">
                      Lorem ipsum eu nunc commodo posuere et sit amet ligula.
                    </p>
                  </a>
                </div>
                <div className="flex-none mt-auto bg-white rounded-b rounded-t-none overflow-hidden shadow-lg p-6">
                  <div className="flex items-center justify-between">
                    <img className="w-8 h-8 rounded-full mr-4 avatar" data-tippy-content="Author Name" src="http://i.pravatar.cc/300" alt="Avatar of Author" />
                    <p className="text-gray-600 text-xs md:text-sm">1 MIN READ</p>
                  </div>
                </div>
              </div>




              <div className="w-full md:w-2/3 p-6 flex flex-col flex-grow flex-shrink">
                <div className="flex-1 bg-white rounded-t rounded-b-none overflow-hidden shadow-lg">
                  <a href="#" className="flex flex-wrap no-underline hover:no-underline">
                    <img src="https://source.unsplash.com/collection/325867/800x600" className="h-full w-full rounded-t pb-6" />
                    <p className="w-full text-gray-600 text-xs md:text-sm px-6">GETTING STARTED</p>
                    <div className="w-full font-bold text-xl text-gray-900 px-6">Lorem ipsum dolor sit amet.</div>
                    <p className="text-gray-800 font-serif text-base px-6 mb-5">
                      Lorem ipsum eu nunc commodo posuere et sit amet ligula.
                    </p>
                  </a>
                </div>
                <div className="flex-none mt-auto bg-white rounded-b rounded-t-none overflow-hidden shadow-lg p-6">
                  <div className="flex items-center justify-between">
                    <img className="w-8 h-8 rounded-full mr-4 avatar" data-tippy-content="Author Name" src="http://i.pravatar.cc/300" alt="Avatar of Author" />
                    <p className="text-gray-600 text-xs md:text-sm">1 MIN READ</p>
                  </div>
                </div>
              </div>


              <div className="w-full md:w-1/3 p-6 flex flex-col flex-grow flex-shrink">
                <div className="flex-1 bg-white rounded-t rounded-b-none overflow-hidden shadow-lg">
                  <a href="#" className="flex flex-wrap no-underline hover:no-underline">
                    <img src="https://source.unsplash.com/collection/1118905/800x600" className="h-full w-full rounded-t pb-6" />
                    <p className="w-full text-gray-600 text-xs md:text-sm px-6">GETTING STARTED</p>
                    <div className="w-full font-bold text-xl text-gray-900 px-6">Lorem ipsum dolor sit amet.</div>
                    <p className="text-gray-800 font-serif text-base px-6 mb-5">
                      Lorem ipsum eu nunc commodo posuere et sit amet ligula.
                    </p>
                  </a>
                </div>
                <div className="flex-none mt-auto bg-white rounded-b rounded-t-none overflow-hidden shadow-lg p-6">
                  <div className="flex items-center justify-between">
                    <img className="w-8 h-8 rounded-full mr-4 avatar" data-tippy-content="Author Name" src="http://i.pravatar.cc/300" alt="Avatar of Author" />
                    <p className="text-gray-600 text-xs md:text-sm">1 MIN READ</p>
                  </div>
                </div>
              </div>

            </div>

          </div>



          <div className="container font-sans bg-green-100 rounded mt-8 p-4 md:p-24 text-center">
            <h2 className="font-bold break-normal text-2xl md:text-4xl">Subscribe to Ghostwind CSS</h2>
            <h3 className="font-bold break-normal  text-gray-600 text-base md:text-xl">Get the latest posts delivered right to your inbox</h3>
            <div className="w-full text-center pt-4">
              <form action="#">
                <div className="max-w-xl mx-auto p-1 pr-0 flex flex-wrap items-center">
                  <input type="email" placeholder="youremail@example.com" className="flex-1 appearance-none rounded shadow p-3 text-gray-600 mr-2 focus:outline-none" />
                  <button type="submit" className="flex-1 mt-4 md:mt-0 block md:inline-block appearance-none bg-green-500 text-white text-base font-semibold tracking-wider uppercase py-4 rounded shadow hover:bg-green-400">Subscribe</button>
                </div>
              </form>
            </div>
          </div>


          <div className="flex w-full items-center font-sans p-8 md:p-24">
            <img className="w-10 h-10 rounded-full mr-4" src="http://i.pravatar.cc/300" alt="Avatar of Author" />
            <div className="flex-1">
              <p className="text-base font-bold md:text-xl leading-none">Ghostwind CSS</p>
              <p className="text-gray-600 text-xs md:text-base">Tailwind CSS version of Ghost's Casper theme by <a className="text-gray-800 hover:text-green-500 no-underline border-b-2 border-green-500" href="https://www.tailwindtoolbox.com">TailwindToolbox.com</a></p>
            </div>
            <div className="justify-end">
              <button className="bg-transparent border border-gray-500 hover:border-green-500 text-xs text-gray-500 hover:text-green-500 font-bold py-2 px-4 rounded-full">Read More</button>
            </div>
          </div>

        </div>


      </div>




      <Script src="https://unpkg.com/popper.js@1/dist/umd/popper.min.js" />
      <Script src="https://unpkg.com/tippy.js@4" />

    </div>





  </>

}

export async function getServerSideProps(context) {

  if (!mongoose.connections[0].readyState) {

    await mongoose.connect(process.env.MONGO_URI);
  }
  let products = await Books.find()

  console.log(products)
  return {
    props: { products: JSON.parse(JSON.stringify(products)) }, // will be passed to the page component as props
  }
}
